# Generated by Django 4.1.7 on 2023-05-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recette', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.TextField()),
                ('ingredients', models.TextField()),
                ('url', models.TextField()),
                ('image', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
    ]
