# Generated by Django 4.1.7 on 2023-05-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recette', '0006_recipe_steps_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='intro',
            field=models.TextField(default='no intro found'),
        ),
    ]
