# Generated by Django 4.1.7 on 2023-05-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recette', '0012_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperating',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Recette.user'),
        ),
    ]
