# Generated by Django 4.1.7 on 2023-05-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recette', '0013_reciperating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperating',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Recette.user'),
        ),
    ]
