# Generated by Django 4.1.7 on 2023-05-03 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recette', '0015_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='recipe',
        ),
    ]
